imports:
  - { resource: "orm_target_entities.yml" }
  - { resource: "@CoreBundle/Resources/config/doctrine.yml" }

doctrine:
  orm:
    dql:
      datetime_functions:
        DATESUB: DoctrineExtensions\Query\Mysql\DateSub
    mappings:
      Provider:
        type: xml
        is_bundle: false
        dir: '/opt/irontec/ivozprovider/library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/Mapping'
        prefix: Ivoz\Provider\Domain\Model
      Ast:
        type: xml
        is_bundle: false
        dir: '/opt/irontec/ivozprovider/library/Ivoz/Ast/Infrastructure/Persistence/Doctrine/Mapping'
        prefix: Ivoz\Ast\Domain\Model
      Kam:
        type: xml
        is_bundle: false
        dir: '/opt/irontec/ivozprovider/library/Ivoz/Kam/Infrastructure/Persistence/Doctrine/Mapping'
        prefix: Ivoz\Kam\Domain\Model
      Cgr:
        type: xml
        is_bundle: false
        dir: '/opt/irontec/ivozprovider/library/Ivoz/Cgr/Infrastructure/Persistence/Doctrine/Mapping'
        prefix: Ivoz\Cgr\Domain\Model
