services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Ivoz\Provider\Domain\Assembler\:
    resource: '/opt/irontec/ivozprovider/library/Ivoz/Provider/Domain/Assembler/*/*'
    exclude: '/opt/irontec/ivozprovider/library/Ivoz/Provider/Domain/Assembler/*/{StoragePathResolver.php}'
    public: true

  ##########################################
  ## Brand
  ##########################################
  Ivoz\Provider\Domain\Assembler\Brand\BrandAssembler:
    arguments:
      $storagePathResolver: '@Service\StoragePathResolverCollection::Brand'

  Ivoz\Provider\Domain\Assembler\Brand\BrandDtoAssembler:
    arguments:
      $storagePathResolver: '@Service\StoragePathResolverCollection::Brand'

  ##########################################
  ## WebPortal
  ##########################################
  Ivoz\Provider\Domain\Assembler\WebPortal\WebPortalAssembler:
    arguments:
      $storagePathResolver: '@Service\StoragePathResolverCollection::WebPortal'

  Ivoz\Provider\Domain\Assembler\WebPortal\WebPortalDtoAssembler:
    arguments:
      $storagePathResolver: '@Service\StoragePathResolverCollection::WebPortal'

  ##########################################
  ## CallCsvReport
  ##########################################
  Ivoz\Provider\Domain\Assembler\CallCsvReport\CallCsvReportAssembler:
    arguments:
      $storagePathResolver: '@Service\StoragePathResolverCollection::CallCsvReport'

  Ivoz\Provider\Domain\Assembler\CallCsvReport\CallCsvReportDtoAssembler:
    arguments:
      $storagePathResolver: '@Service\StoragePathResolverCollection::CallCsvReport'

  ##########################################
  ## FaxesInOut
  ##########################################
  Ivoz\Provider\Domain\Assembler\FaxesInOut\FaxesInOutAssembler:
    public: true
    arguments:
      $storagePathResolver: '@Service\StoragePathResolverCollection::FaxesInOut'

  Ivoz\Provider\Domain\Assembler\FaxesInOut\FaxesInOutDtoAssembler:
    arguments:
      $storagePathResolver: '@Service\StoragePathResolverCollection::FaxesInOut'

  ##########################################
  ## Locution
  ##########################################
  Ivoz\Provider\Domain\Assembler\Locution\LocutionAssembler:
    public: true
    arguments:
      $storagePathResolver: '@Service\StoragePathResolverCollection::Locution'

  Ivoz\Provider\Domain\Assembler\Locution\LocutionDtoAssembler:
    arguments:
      $storagePathResolver: '@Service\StoragePathResolverCollection::Locution'

  ##########################################
  ## Invoice
  ##########################################
  Ivoz\Provider\Domain\Assembler\Invoice\InvoiceAssembler:
    arguments:
      $storagePathResolver: '@Service\StoragePathResolverCollection::Invoice'

  Ivoz\Provider\Domain\Assembler\Invoice\InvoiceDtoAssembler:
    arguments:
      $storagePathResolver: '@Service\StoragePathResolverCollection::Invoice'

  ##########################################
  ## MusicOnHold
  ##########################################
  Ivoz\Provider\Domain\Assembler\MusicOnHold\MusicOnHoldAssembler:
    arguments:
      $storagePathResolver: '@Service\StoragePathResolverCollection::MusicOnHold'

  Ivoz\Provider\Domain\Assembler\MusicOnHold\MusicOnHoldDtoAssembler:
    arguments:
      $storagePathResolver: '@Service\StoragePathResolverCollection::MusicOnHold'

  ##########################################
  ## Recording
  ##########################################
  Ivoz\Provider\Domain\Assembler\Recording\RecordingAssembler:
    arguments:
      $storagePathResolver: '@Service\StoragePathResolverCollection::Recording'

  Ivoz\Provider\Domain\Assembler\Recording\RecordingDtoAssembler:
    arguments:
      $storagePathResolver: '@Service\StoragePathResolverCollection::Recording'

  ##########################################
  ## DestinationRateGroup
  ##########################################
  Ivoz\Provider\Domain\Assembler\DestinationRateGroup\DestinationRateGroupAssembler:
    arguments:
      $storagePathResolver: '@Service\StoragePathResolverCollection::DestinationRateGroup'

  Ivoz\Provider\Domain\Assembler\DestinationRateGroup\DestinationRateGroupDtoAssembler:
    arguments:
      $storagePathResolver: '@Service\StoragePathResolverCollection::DestinationRateGroup'

  ##########################################
  ## VoicemailMessage
  ##########################################
  Ivoz\Provider\Domain\Assembler\VoicemailMessage\VoicemailMessageAssembler:
    arguments:
      $storagePathResolver: '@Service\StoragePathResolverCollection::VoicemailMessage'

  Ivoz\Provider\Domain\Assembler\VoicemailMessage\VoicemailMessageDtoAssembler:
    arguments:
      $storagePathResolver: '@Service\StoragePathResolverCollection::VoicemailMessage'