production:
  entity: Ivoz\Provider\Domain\Model\CallCsvScheduler\CallCsvScheduler
  fields:
    name:
      title: _('Name')
      type: text
      trim: both
      required: true
      maxLength: 40
      default: true
    callDirection:
      title: _('Direction')
      type: select
      required: false
      defaultValue: 'outbound'
      source:
        data: inline
        values:
          'outbound':
            title: _('Outbound')
            visualFilter:
              show: ["carrier"]
              hide: []
          'inbound':
            title: _('Inbound')
            visualFilter:
              show: []
              hide: ["carrier"]
          '__null__':
            title:_('Both')
            visualFilter:
              show: []
              hide: ["carrier"]
    frequency:
      title: _('Frequency')
      type: number
      required: true
      defaultValue: 1
      source:
        control: Spinner
        min: 1
    unit:
      title: _('Unit')
      type: select
      required: true
      defaultValue: 'month'
      source:
        data: inline
        values:
          'day': _('Day')
          'week': _('Week')
          'month': _('Month')
    email:
      title: ngettext('Email', 'Emails', 1)
      type: text
      trim: both
      defaultValue: ''
      maxLength: 140
      info:
        type: box
        position: left
        icon: help
        text: _("Leave empty if no mail is needed (just generate CSV).")
        label: _("Need help?")
      default: true
    lastExecution:
      title: _('Last execution')
      type: ghost
      dirty: true
      source:
        class: IvozProvider_Klear_Ghost_SchedulerSuccess
        method: getCallCsvSchedulerLastExecutionReport
    nextExecution:
      title: _('Next execution')
      type: picker
      required: true
      source:
        control: datetime
        settings:
          disabled: 'false'
    brand:
      title: ngettext('Brand', 'Brands', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\Brand\Brand
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            Brand.name: asc
    companyType:
      title: ngettext('Client Type', 'Client Types', 1)
      type: select
      attributes:
        data-autofilter-select-by-data:
          company: type
      required: true
      source:
        data: inline
        values:
          '_NULL_':
            title: _('All')
            visualFilter:
              show: ["callCsvNotificationTemplate"]
              hide: ["company", "residentialDevice", "retailAccount", "ddi"]
          vpbx:
            title: _('vPBX')
            visualFilter:
              show: ["company"]
              hide: ["residentialDevice", "retailAccount", "callCsvNotificationTemplate"]
          retail:
            title: _('Retail')
            visualFilter:
              show: ["company", "retailAccount"]
              hide: ["residentialDevice", "callCsvNotificationTemplate"]
          residential:
            title: _('Residential')
            visualFilter:
              show: ["company", "residentialDevice"]
              hide: ["retailAccount", "callCsvNotificationTemplate"]
          wholesale:
            title: _('Wholesale')
            visualFilter:
              show: ["company"]
              hide: ["retailAccount", "residentialDevice", "callCsvNotificationTemplate"]
    company:
      title: ngettext('Client', 'Clients', 1)
      type: select
      required: true
      attributes:
        data-autofilter-select-by-data:
          retailAccount: company
          residentialDevice: company
          ddi: company
      source:
        data: mapper
        'null': " "
        config:
          entity: \Ivoz\Provider\Domain\Model\Company\Company
          filterClass: IvozProvider_Klear_Filter_Brand
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            Company.name: asc
          extraDataAttributes:
            type: type
          visualFilter:
            name:
              __default__:
                show:
                - ddi
                hide: []
              'null':
                show: []
                hide:
                - ddi
    callCsvNotificationTemplate:
      title: ngettext('Notification template', 'Notification templates', 1)
      type: select
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\NotificationTemplate\NotificationTemplate
          filterClass: IvozProvider_Klear_Filter_NotificationTemplateCallCsv
          fieldName:
            fields:
            - name
            template: '%name%'
        'null': _("Use generic template")
    ddi:
      title: _('DDI')
      type: select
      source:
        data: mapper
        'null': _("All")
        config:
          entity: \Ivoz\Provider\Domain\Model\Ddi\Ddi
          filterClass: IvozProvider_Klear_Filter_OutgoingDDI
          fieldName:
            fields:
              - ddie164
            template: '%ddie164%'
          order:
            Ddi.ddie164: asc
          extraDataAttributes:
            company: companyId
    carrier:
      title: _('Carrier')
      type: select
      source:
        data: mapper
        'null': _("All")
        config:
          entity: \Ivoz\Provider\Domain\Model\Carrier\Carrier
          filterClass: IvozProvider_Klear_Filter_Brand
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            Carrier.name: asc
    retailAccount:
      title: _('Retail Account')
      type: select
      source:
        data: mapper
        'null': _("All")
        config:
          entity: \Ivoz\Provider\Domain\Model\RetailAccount\RetailAccount
          filterClass: IvozProvider_Klear_Filter_Brand
          fieldName:
            fields:
              - name
            template: '%name%'
          extraDataAttributes:
            company: companyId
          order:
            RetailAccount.name: asc
    residentialDevice:
      title: _('Residential Device')
      type: select
      source:
        data: mapper
        'null': _("All")
        config:
          entity: \Ivoz\Provider\Domain\Model\ResidentialDevice\ResidentialDevice
          filterClass: IvozProvider_Klear_Filter_Brand
          fieldName:
            fields:
              - name
            template: '%name%'
          extraDataAttributes:
            company: companyId
          order:
            ResidentialDevice.name: asc
staging:
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
