production:
  entity: \Ivoz\Provider\Domain\Model\Domain\Domain
  fields: 
    domain:
      title: _('Domain')
      type: text
      trim: both
      required: true
      maxLength: 255
      default: true
    scope:
      title: _('Scope')
      type: ghost
      source:
        class: IvozProvider_Klear_Ghost_DomainsScope
        method: getData
    pointsTo:
      title: _('Points to')
      type: select
      defaultValue: proxyusers
      source:
        data: inline
        values:
          'proxyusers': ngettext('Proxy Users', 'Proxies Users', 1)
          'proxytrunks': ngettext('Proxy Trunks', 'Proxy Trunks', 1)
    description:
      title: _('Description')
      type: text
      trim: both
      maxLength: 500

staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
