########################################
## Raw
########################################
Ivoz\Kam\Domain\Model\UsersLocation\RegistrationStatus:
  itemOperations: []
  collectionOperations: []

Ivoz\Kam\Domain\Model\UsersCdr\UsersCdr:
  attributes:
    access_control: '"ROLE_BRAND_ADMIN" in roles'
