services:
  _defaults:
    autowire: false
    public: false

  Ivoz\Provider\Domain\Service\Carrier\SyncBalances:
    public: true
    autowire: true

  Ivoz\Provider\Domain\Service\Carrier\AbstractBalanceOperation:
    abstract:  true
    arguments:
      $entityTools: '@Ivoz\Core\Domain\Service\EntityTools'
      $logger: '@logger'
      $carrierBalanceService: '@Ivoz\Cgr\Infrastructure\Cgrates\Service\CarrierBalanceService'
      $syncBalanceService: '@Ivoz\Provider\Domain\Service\Carrier\SyncBalances'
      $carrierRepository: '@Ivoz\Provider\Domain\Model\Carrier\CarrierRepository'
      $createBalanceMovementByCarrier: '@Ivoz\Provider\Domain\Service\BalanceMovement\CreateByCarrier'

  Ivoz\Provider\Domain\Service\Carrier\IncrementBalance:
    public: true
    autowire: false
    parent: Ivoz\Provider\Domain\Service\Carrier\AbstractBalanceOperation

  Ivoz\Provider\Domain\Service\Carrier\DecrementBalance:
    public: true
    autowire: false
    parent: Ivoz\Provider\Domain\Service\Carrier\AbstractBalanceOperation
