services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ivoz\Ast\Infrastructure\Asterisk\ARI\ARIConnector:
    arguments:
      $userName: '%ari_user%'
      $password: '%ari_password%'
      $port: '%ari_port%'

###############################################
## TEST
###############################################
when@test:
  services:
    _defaults:
      autowire: true
      autoconfigure: true
      public: false

    Ivoz\Ast\Infrastructure\Asterisk\ARI\ARIConnector:
      class: Ivoz\Ast\Infrastructure\Asterisk\ARI\FakeARIConnector
      arguments:
        $userName: ''
        $password: ''
        $port: ''