services:
  _defaults:
    autowire: true
    public: false

  ###############################################
  ## RPC Clients
  ###############################################

  Ivoz\Kam\Infrastructure\Kamailio\RpcClient::Trunks:
    class: Ivoz\Kam\Infrastructure\Kamailio\RpcClient
    factory: ['Ivoz\Kam\Infrastructure\Kamailio\RpcClient', 'factory']
    arguments:
      - 'trunks.ivozprovider.local:8001'
      - {'connect_timeout': 2, 'timeout': 0}

  Ivoz\Kam\Infrastructure\Kamailio\RpcClient::Users:
    class: Ivoz\Kam\Infrastructure\Kamailio\RpcClient
    factory: ['Ivoz\Kam\Infrastructure\Kamailio\RpcClient', 'factory']
    arguments:
      - 'users.ivozprovider.local:8000'
      - { 'connect_timeout': 2, 'timeout': 0 }

  ###############################################
  ## Kam API Clients
  ###############################################

  # Trunks RPC client
  Ivoz\Kam\Infrastructure\Kamailio\TrunksClient:
    arguments:
      $rpcClient: '@Ivoz\Kam\Infrastructure\Kamailio\RpcClient::Trunks'
  Ivoz\Kam\Domain\Service\TrunksClientInterface:
    alias: 'Ivoz\Kam\Infrastructure\Kamailio\TrunksClient'
    public: true

  # Users RPC client
  Ivoz\Kam\Infrastructure\Kamailio\UsersClient:
    arguments:
      $rpcClient: '@Ivoz\Kam\Infrastructure\Kamailio\RpcClient::Users'
  Ivoz\Kam\Domain\Service\UsersClientInterface:
    alias: 'Ivoz\Kam\Infrastructure\Kamailio\UsersClient'

###############################################
## TEST
###############################################
when@test:
  services:
    _defaults:
      autowire: true
      public: false

    Ivoz\Kam\Infrastructure\Kamailio\RpcClient::Trunks:
      class: Ivoz\Kam\Infrastructure\Kamailio\FakeRpcClient
      factory: ['Ivoz\Kam\Infrastructure\Kamailio\FakeRpcClient', 'factory']
      arguments: ['trunks.ivozprovider.local:8001']

    Ivoz\Kam\Infrastructure\Kamailio\RpcClient::Users:
      class: Ivoz\Kam\Infrastructure\Kamailio\FakeRpcClient
      factory: ['Ivoz\Kam\Infrastructure\Kamailio\FakeRpcClient', 'factory']
      arguments: ['trunks.ivozprovider.local:8001']

    # Trunks RPC client
    Ivoz\Kam\Infrastructure\Kamailio\TrunksClient:
      arguments:
        $rpcClient: '@Ivoz\Kam\Infrastructure\Kamailio\RpcClient::Trunks'

    # Users RPC client
    Ivoz\Kam\Infrastructure\Kamailio\UsersClient:
      arguments:
        $rpcClient: '@Ivoz\Kam\Infrastructure\Kamailio\RpcClient::Users'
