#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include conf.d/documentationLink.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: administratorRelPublicSections_screen
  screens: &administratorRelPublicSections_screensLink
    administratorRelPublicSectionsList_screen: &administratorRelPublicSectionsList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *AdministratorRelPublicSections
      class: fa fa-users red
      title: _("List of %s %2s", ngettext('Administrator access privilege', 'Administrator access privileges', 0), "[format| (%parent%)]")
      info:
        <<: *documentationLink
        href: "/doc/en/administration_portal/platform/access_privileges.html"
      fields:
        options:
          title: _("Options")
          screens:
            administratorRelPublicSectionsEdit_screen: true
          dialogs:
            administratorRelPublicSectionsDel_dialog: true
          default: administratorRelPublicSectionsEdit_screen
        order: &AdministratorRelPublicSections_orderLink
          email: true
          username: true
          pass: true
          timezone: true
          name: true
          lastname: true
          active: true
          restricted: true
        blacklist:
          email: true
          pass: true
          name: true
          lastname: true
          timezone: true
          brand: true
          company: true
      options: 
        title: _("Options")
        screens:
          administratorRelPublicSectionsNew_screen: true
        dialogs:
          administratorRelPublicSectionsDel_dialog: true

    administratorRelPublicSectionsNew_screen: &administratorRelPublicSectionsNew_screenLink
      <<: *AdministratorRelPublicSections
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Administrator access privilege', 'Administrator access privileges', 1))
      shortcutOption: N

    administratorRelPublicSectionsEdit_screen: &administratorRelPublicSectionsEdit_screenLink
      <<: *AdministratorRelPublicSections
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Administrator access privilege', 'Administrator access privileges', 1), "[format| (%item%)]")
      fields:
        order:
          <<: *AdministratorRelPublicSections_orderLink
#        blacklist:
#          administrator: true

  dialogs: &administratorRelPublicSections_dialogsLink
    administratorRelPublicSectionsDel_dialog: &administratorRelPublicSectionsDel_dialogLink
      <<: *AdministratorRelPublicSections
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Administrator access privilege', 'Administrator access privileges', 1))
      description: _("Do you want to delete this %s?", ngettext('Administrator access privilege', 'Administrator access privileges', 1))
      message: _("%s successfully deleted.", ngettext('Administrator access privilege', 'Administrator access privileges', 1))
      multiItem: 1
      labelOnList: 1

staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
