#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include conf.d/documentationLink.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: bruteForceAttacksList_screen
  screens: &bruteForceAttacks_screensLink
    bruteForceAttacksList_screen: &bruteForceAttacksList_screenLink
      controller: list
      forcedValues:
        <<: *forcedBrand
      pagination:
        items: 100
      order:
        field:
        - BannedAddress.lastTimeBanned desc
      <<: *BannedAddresses
      class: ui-silk-door
      title: _("List of %s %2s", ngettext('Banned IP address', 'Banned IP addresses', 0), "[format| (%parent%)]")
      rawCondition: "BannedAddress.blocker = 'antibruteforce'"
      info:
        <<: *documentationLink
        href: "/doc/en/administration_portal/brand/views/bruteforce_attacks.html"
      fields: &bruteForceAttacks_fieldsLink
        order:
          company: true
          aor: true
          ip: true
          lastTimeBanned: true
        blacklist:
          blocker: true
          description: true
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
