#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include conf.d/documentationLink.yaml
#include HuntGroupMembersList.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: huntGroupsList_screen
  screens: &huntGroups_screensLink
    huntGroupsList_screen: &huntGroupsList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *HuntGroups
      class: ui-silk-group-go
      title: _("List of %s %2s", ngettext('Hunt Group', 'Hunt Groups', 0), "[format| (%parent%)]")
      info:
        <<: *documentationLink
        href: "/doc/en/administration_portal/client/vpbx/routing_endpoints/hunt_groups.html"
      forcedValues:
        <<: *forcedCompany
      fields:
        options:
          title: _("Options")
          screens:
            huntGroupsEdit_screen: $[${auth.acls.HuntGroups.update} && ${auth.companyVPBX}]
            huntGroupMembersList_screen: $[${auth.acls.HuntGroupMembers.read} && ${auth.companyVPBX}]
            huntGroupMembersFilterRingAllList_screen: $[${auth.acls.HuntGroupMembers.read} && ${auth.companyVPBX}]
            huntGroupMembersFilterRandomList_screen: $[${auth.acls.HuntGroupMembers.read} && ${auth.companyVPBX}]
          dialogs:
            huntGroupsDel_dialog: $[${auth.acls.HuntGroups.delete} && ${auth.companyVPBX}]
          default: huntGroupsEdit_screen
        blacklist:
          ringAllTimeout: true
          noAnswerTargetType: true
          noAnswerLocution: true
          noAnswerNumberCountry: true
          noAnswerNumberValue: true
          noAnswerExtension: true
          noAnswerVoicemail: true
          preventMissedCalls: true
          allowCallForwards: true
      options:
        title: _("Options")
        screens:
          huntGroupsNew_screen: $[${auth.acls.HuntGroups.create} && ${auth.companyVPBX}]
        dialogs:
          huntGroupsDel_dialog: $[${auth.acls.HuntGroups.delete} && ${auth.companyVPBX}]
    huntGroupsNew_screen: &huntGroupsNew_screenLink
      <<: *HuntGroups
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Hunt Group', 'Hunt Groups', 1))
      shortcutOption: N
      defaultValues:
        noAnswerNumberCountry: ${auth.companyCountryId}
      forcedValues:
        <<: *forcedCompany
      fields:
        blacklist: &huntGroupsBlacklist_Link
      fixedPositions: &huntGroupsFixedPositions_Link
        group0:
          label: _("Basic Configuration")
          colsPerRow: 12
          fields:
            name: 6
            description: 6
            preventMissedCalls: 5
            allowCallForwards: 5
            strategy: 4
            ringAllTimeOut: 4
        group1:
          label: _("No answer configuration")
          colsPerRow: 6
          fields:
            noAnswerLocution: 5
            noAnswerTargetType: 2
            noAnswerNumberCountry: 2
            noAnswerNumberValue: 2
            noAnswerExtension: 3
            noAnswerVoicemail: 3
    huntGroupsEdit_screen: &huntGroupsEdit_screenLink
      <<: *HuntGroups
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Hunt Group', 'Hunt Groups', 1), "[format| (%item%)]")
      forcedValues:
        <<: *forcedCompany
      defaultValues:
        noAnswerNumberCountry: ${auth.companyCountryId}
      fields:
        blacklist:
          <<: *huntGroupsBlacklist_Link
      fixedPositions:
        <<: *huntGroupsFixedPositions_Link

    # HuntGroupMembers
    <<: *huntGroupMembers_screensLink
    huntGroupMembersList_screen:
      <<: *huntGroupMembersList_screenLink
      title: _("List of %s %2s", ngettext('Member', 'Members', 0), "[format| (%parent%)]")
      class: ui-silk-group-go
      filterField: HuntGroup
      parentOptionCustomizer:
        - IvozProvider_Klear_Options_OptionsCustomizerFilterForHuntGroup
        - recordCount

    huntGroupMembersEdit_screen:
      <<: *huntGroupMembersEdit_screenLink
      title: _("Edit %s", ngettext('Member', 'Members', 1))
      filterField: HuntGroup

    huntGroupMembersNew_screen:
      <<: *huntGroupMembersNew_screenLink
      title: _("Add %s %2s", ngettext('Member', 'Members', 1), "[format| (%parent%)]")
      filterField: HuntGroup

    # HuntGroupMembers filter by "ringAll"
    huntGroupMembersFilterRingAllList_screen:
      <<: *huntGroupMembersList_screenLink
      title: _("List of %s %2s", ngettext('Member', 'Members', 0), "[format| (%parent%)]")
      class: ui-silk-group-go
      filterField: HuntGroup
      parentOptionCustomizer:
        - IvozProvider_Klear_Options_OptionsCustomizerFilterForHuntGroup
        - recordCount
      fields:
        order:
          routeType: true
          target: true
        blacklist:
          timeoutTime: true
          numberCountry: true
          numberValue: true
          user: true
          priority: true
        options:
          title: _("Options")
          screens:
            huntGroupMembersFilterRingAllEdit_screen: ${auth.acls.HuntGroupMembers.update}
          dialogs:
            huntGroupMembersDel_dialog: ${auth.acls.HuntGroupMembers.delete}
          default: huntGroupMembersFilterRingAllEdit_screen
      options:
        title: _("Options")
        screens:
          huntGroupMembersFilterRingAllNew_screen: ${auth.acls.HuntGroupMembers.create}
        dialogs:
          huntGroupMembersDel_dialog: ${auth.acls.HuntGroupMembers.delete}
    huntGroupMembersFilterRingAllEdit_screen:
      <<: *huntGroupMembersEdit_screenLink
      title: _("Edit %s", ngettext('Member', 'Members', 1))
      filterField: HuntGroup
      fields:
        blacklist:
          timeoutTime: true
          priority: true
          user: true
          numberValue: true
          numberCountry: true
        readOnly:
          target: true
          routeType: true

    huntGroupMembersFilterRingAllNew_screen:
      <<: *huntGroupMembersNew_screenLink
      title: _("Add %s %2s", ngettext('Member', 'Members', 1), "[format| (%parent%)]")
      filterField: HuntGroup
      fields:
        blacklist:
          timeoutTime: true
          priority: true
          target: true

    # HuntGroupMembers filter by "random"
    huntGroupMembersFilterRandomList_screen:
      <<: *huntGroupMembersList_screenLink
      title: _("List of %s %2s", ngettext('Member', 'Members', 0), "[format| (%parent%)]")
      class: ui-silk-group-go
      filterField: HuntGroup
      parentOptionCustomizer:
        - IvozProvider_Klear_Options_OptionsCustomizerFilterForHuntGroup
        - recordCount
      fields:
        order:
          routeType: true
          target: true
        blacklist:
          numberCountry: true
          numberValue: true
          user: true
          priority: true
        options:
          title: _("Options")
          screens:
            huntGroupMembersFilterRandomEdit_screen: ${auth.acls.HuntGroupMembers.update}
          dialogs:
            huntGroupMembersDel_dialog: ${auth.acls.HuntGroupMembers.delete}
          default: huntGroupMembersFilterRandomEdit_screen
      options:
        title: _("Options")
        screens:
          huntGroupMembersFilterRandomNew_screen: ${auth.acls.HuntGroupMembers.create}
        dialogs:
          huntGroupMembersDel_dialog: ${auth.acls.HuntGroupMembers.delete}
    huntGroupMembersFilterRandomEdit_screen:
      <<: *huntGroupMembersEdit_screenLink
      title: _("Edit %s", ngettext('Member', 'Members', 1))
      filterField: HuntGroup
      fields:
        order:
          routeType: true
          target: true
        blacklist:
          numberCountry: true
          numberValue: true
          user: true
          priority: true
        readOnly:
          target: true
          routeType: true

    huntGroupMembersFilterRandomNew_screen:
      <<: *huntGroupMembersNew_screenLink
      title: _("Add %s %2s", ngettext('Member', 'Members', 1), "[format| (%parent%)]")
      filterField: HuntGroup
      fields:
        blacklist:
          priority: true
          target: true

  dialogs: &huntGroups_dialogsLink
    huntGroupsDel_dialog: &huntGroupsDel_dialogLink
      <<: *HuntGroups
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Hunt Group', 'Hunt Groups', 1))
      description: _("Do you want to delete this %s?", ngettext('Hunt Group', 'Hunt Groups', 1))
      message: _("%s successfully deleted.", ngettext('Hunt Group', 'Hunt Groups', 1))
      multiItem: 1
      labelOnList: 1

    <<: *huntGroupMembers_dialogsLink
    huntGroupMembersDel_dialog:
      <<: *huntGroupMembersDel_dialogLink
      title: _("Delete %s", ngettext('Member', 'Members', 1))

staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
