# For full configuration reference please see:
# http://gearmanbundle.readthedocs.io/en/latest/configuration.html
#
# At least you need to provide `resources` or `bundles` configuration in order for your
# worker annotations to be discoverable.
gearman:
    servers:
        jobs.ivozprovider.local:
            host: jobs.ivozprovider.local
    resources:
        - ../src/Worker/

