# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
imports:
    - { resource: "@ApiBundle/Resources/config/services.yml" }

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Service\UserProvider::User:
    class: Service\UserProvider
    arguments:
      $identifierField: 'email'
      $entityClass: 'Ivoz\Provider\Domain\Model\User\User'

  Service\UserProvider::Administrator:
    class: Service\UserProvider
    arguments:
      $identifierField: 'username'
      $entityClass: 'Ivoz\Provider\Domain\Model\Administrator\Administrator'

  Service\AuthEndpointDecorator:
    decorates: 'api_platform.swagger.normalizer.documentation'
    decoration_priority: 5
    arguments:
      $decoratedNormalizer:
        '@Service\AuthEndpointDecorator.inner'

  Ivoz\Api\Operation\ExchangeToken:
    arguments:
      $userProvider: '@Service\UserProvider::Administrator'
      $requiredInputRole: 'ROLE_BRAND_ADMIN'
      $requiredOutputRole: 'ROLE_COMPANY_ADMIN'

  Ivoz\Api\Core\Security\DataAccessControlParser:
    calls:
      - [ addRepository, ['matchListRepository', '@=service("doctrine.orm.entity_manager").getRepository("Ivoz\\Provider\\Domain\\Model\\MatchList\\MatchList")']]
      - [ addRepository, ['ratingProfileRepository', '@=service("doctrine.orm.entity_manager").getRepository("Ivoz\\Provider\\Domain\\Model\\RatingProfile\\RatingProfile")']]
      - [ addRepository, ['companyRelRoutingTagRepository', '@=service("doctrine.orm.entity_manager").getRepository("Ivoz\\Provider\\Domain\\Model\\CompanyRelRoutingTag\\CompanyRelRoutingTag")']]
      - [ addRepository, ['brandServiceRepository', '@=service("doctrine.orm.entity_manager").getRepository("Ivoz\\Provider\\Domain\\Model\\BrandService\\BrandService")']]

  #######################################
  ## Controllers
  #######################################
  Controller\Auth\:
    resource: '../src/Controller/Auth/*'
    tags: ['controller.service_arguments']

  Controller\My\:
    resource: '../src/Controller/My/*'
    tags: ['controller.service_arguments']

  Controller\Provider\:
    resource: '../src/Controller/Provider/*'
    tags: ['controller.service_arguments']

  #######################################
  ## API Normalizers
  #######################################
  billable_call_normalizer.json:
    class: 'Service\BillableCallNormalizer'
    decorates: 'Ivoz\Api\Json\Serializer\Normalizer\EntityNormalizer'
    decoration_priority: 1
    arguments:
      $decoratedNormalizer: '@billable_call_normalizer.json.inner'

  billable_call_normalizer.jsonld:
    class: 'Service\BillableCallNormalizer'
    decorates: 'Ivoz\Api\JsonLd\Serializer\Normalizer\EntityNormalizer'
    decoration_priority: 1
    arguments:
      $decoratedNormalizer: '@billable_call_normalizer.jsonld.inner'

  billable_call_normalizer.csv:
    class: 'Service\BillableCallNormalizer'
    decorates: 'Ivoz\Api\Csv\Serializer\Normalizer\EntityNormalizer'
    decoration_priority: 1
    arguments:
      $decoratedNormalizer: '@billable_call_normalizer.csv.inner'
