Ivoz\Provider\Domain\Model\BillableCallHistoric\BillableCallHistoric:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\BillableCallHistoricDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: BillableCallHistorics
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: NONE
