Ivoz\Provider\Domain\Model\CallCsvScheduler\CallCsvSchedulerAbstract:
  type: mappedSuperclass
  uniqueConstraints:
    CallCsvScheduler_brand_name:
      columns:
        - brandId
        - name
  fields:
    name:
      type: string
      nullable: false
      length: 40
      options:
        fixed: false
    unit:
      type: string
      nullable: false
      length: 30
      options:
        fixed: false
        comment: '[enum:day|week|month]'
        default: 'month'
    frequency:
      type: smallint
      nullable: false
      options:
        unsigned: true
    callDirection:
      type: string
      nullable: true
      length: null
      options:
        fixed: false
        comment: '[enum:inbound|outbound]'
        default: 'outbound'
      column: callDirection
    email:
      type: string
      nullable: false
      length: 140
      options:
        fixed: false
    lastExecution:
      type: datetime
      nullable: true
      column: lastExecution
    lastExecutionError:
      type: string
      nullable: true
      length: 300
      options:
        fixed: false
      column: lastExecutionError
    nextExecution:
      type: datetime
      nullable: true
      column: nextExecution
  manyToOne:
    brand:
      targetEntity: \Ivoz\Provider\Domain\Model\Brand\BrandInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        brandId:
          referencedColumnName: id
          nullable: true
          onDelete: cascade
      orphanRemoval: false
    company:
      targetEntity: \Ivoz\Provider\Domain\Model\Company\CompanyInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        companyId:
          referencedColumnName: id
          nullable: true
          onDelete: cascade
      orphanRemoval: false
    callCsvNotificationTemplate:
      targetEntity: \Ivoz\Provider\Domain\Model\NotificationTemplate\NotificationTemplateInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        callCsvNotificationTemplateId:
          referencedColumnName: id
          nullable: true
          onDelete: set null
      orphanRemoval: false
    ddi:
      targetEntity: \Ivoz\Provider\Domain\Model\Ddi\DdiInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        ddiId:
          referencedColumnName: id
          nullable: true
          onDelete: set null
      orphanRemoval: false
    carrier:
      targetEntity: \Ivoz\Provider\Domain\Model\Carrier\CarrierInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        carrierId:
          referencedColumnName: id
          nullable: true
          onDelete: set null
      orphanRemoval: false
    retailAccount:
      targetEntity: \Ivoz\Provider\Domain\Model\RetailAccount\RetailAccountInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        retailAccountId:
          referencedColumnName: id
          nullable: true
          onDelete: set null
      orphanRemoval: false
    residentialDevice:
      targetEntity: \Ivoz\Provider\Domain\Model\ResidentialDevice\ResidentialDeviceInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        residentialDeviceId:
          referencedColumnName: id
          nullable: true
          onDelete: set null
      orphanRemoval: false