Ivoz\Provider\Domain\Model\MaxUsageNotification\MaxUsageNotification:
  repositoryClass: Ivoz\Provider\Infrastructure\Persistence\Doctrine\MaxUsageNotificationDoctrineRepository
  type: entity
  changeTrackingPolicy: DEFERRED_EXPLICIT
  table: MaxUsageNotifications
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
