imports:
    - { resource: "@ApiBundle/Resources/config/api_platform_base.yml" }

api_platform:
    description: 'Platform REST API'
    version: 3.0
    collection:
        pagination:
            # The maximum number of items per page.
            maximum_items_per_page: 10000