#index:
#    path: /
#    controller: App\Controller\DefaultController::index

invoicer:
  path: /invoicer
  controller: Worker\Invoices::create

cgrates-reload:
  path: /cgrates-reloader
  controller: Worker\Cgrates::reload

rates-import:
  path: /rates-import
  controller: Worker\Rates::import

multimedia-encoder:
  path: /multimedia-encoder
  controller: Worker\Multimedia::encode

kam-rpc-request:
  path: /kam-rpc-request
  controller: Worker\KamRpc::send

kam-rpc-delayed:
  path: /kam-rpc-delayed
  controller: Worker\KamRpc::delayed

asterisk-dialplan-reload:
  path: /asterisk-dialplan-reload
  controller: Worker\AsteriskDialplan::reload

asterisk-hint-update:
  path: /asterisk-hint-update
  controller: Worker\AsteriskHintUpdater::send