doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        schema_filter: "/^(?!kam_version|changelog|sm_costs|tp_versions$).*/"

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'

        # only needed for MySQL
        charset: utf8mb4
        default_table_options:
            collate: utf8mb4_unicode_ci

        # backtrace queries in profiler (increases memory usage per request)
        #profiling_collect_backtrace: '%kernel.debug%'
    orm:
        mappings:
            JWTRefreshTokenEntity:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'Gesdinet\JWTRefreshTokenBundle\Entity'
